# Generated by Django 4.0.4 on 2022-04-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.CharField(max_length=500)),
                ('shortcode', models.CharField(max_length=100)),
                ('last_seen_date', models.DateTimeField()),
                ('redirect_count', models.IntegerField()),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
