# Generated by Django 4.0.4 on 2022-04-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_alter_url_last_seen_date_alter_url_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='redirect_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
